
package cn.com.pengyue.vo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebService", targetNamespace = "http://www.pengyue.com.cn/", wsdlLocation = "http://localhost:8080/overseas_infomation/webservices?wsdl")
public class WebService_Service
    extends Service
{

    private final static URL WEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.com.pengyue.vo.ws.WebService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.com.pengyue.vo.ws.WebService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/overseas_infomation/webservices?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/overseas_infomation/webservices?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICE_WSDL_LOCATION = url;
    }

    public WebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebService_Service() {
        super(WEBSERVICE_WSDL_LOCATION, new QName("http://www.pengyue.com.cn/", "WebService"));
    }

    /**
     * 
     * @return
     *     returns WebService
     */
    @WebEndpoint(name = "WebServicePort")
    public WebService getWebServicePort() {
        return super.getPort(new QName("http://www.pengyue.com.cn/", "WebServicePort"), WebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService
     */
    @WebEndpoint(name = "WebServicePort")
    public WebService getWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.pengyue.com.cn/", "WebServicePort"), WebService.class, features);
    }

}
